[package]
name = "openfoamparser-rust"
version = "0.1.0"
authors = ["Lukas Stratmann <stratmann@ccs-labs.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nalgebra = "0.24.0"
